# **Clasifikation masalasini 4 ta modelda ishni boshlaymiz**

In [1]:
# kerakli kutubxonalarni chaqirib olamiz

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as snb
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report

from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier


In [2]:
# pandas orqali df o'zgaruvchiga datasetimizni bog'lemiz

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/exam/Carseats.csv")

# head() funksiya orqali dataset boshida 5 ta qator ma'lumotlarni ko'ramiz
df.head()

Sales  CompPrice  Income  Advertising  Population Price ShelveLoc  Age  \
0   9.50        138      73           11         276   120       Bad   42   
1  11.22        111      48           16         260    83      Good   65   
2  10.06        113      35           10         269    80    Medium   59   
3   7.40        117     100            4         466    97    Medium   55   
4   4.15        141      64            3         340   128       Bad   38   

  Education Urban   US  
0        17   Yes  Yes  
1        10   Yes  Yes  
2        12   Yes  Yes  
3        14   Yes  Yes  
4        13   Yes   No

In [3]:
# info() funksiya orqali dataset haqida umumiy ma'lumot olamiz
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64  
 2   Income       400 non-null    int64  
 3   Advertising  400 non-null    int64  
 4   Population   400 non-null    int64  
 5   Price        400 non-null    object 
 6   ShelveLoc    399 non-null    object 
 7   Age          400 non-null    int64  
 8   Education    400 non-null    object 
 9   Urban        400 non-null    object 
 10  US           397 non-null    object 
dtypes: float64(1), int64(5), object(5)
memory usage: 34.5+ KB


In [4]:
# isnull() funksiyasi orqali missing value borligini, sum() orqali ularning umumiy sonini aniqlaymiz
df.isnull().sum()

Sales          0
CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      1
Age            0
Education      0
Urban          0
US             3
dtype: int64

In [6]:
# missing value larni to'ldirishimz kerak
label_encoder = LabelEncoder()

for column in df.columns:
    if df[column].isnull().sum()>0:
        if df[column].dtype=='object':
            df[column].fillna(df[column].mode()[0], inplace=True)
            # df[column] = label_encoder.fit_transform(df[column])

        else:
            df[column].fillna(f[column].mean(), inplace=True)

    # numerical ga o'tkazamiz
    df[column] = label_encoder.fit_transform(df[column])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sales        400 non-null    int64
 1   CompPrice    400 non-null    int64
 2   Income       400 non-null    int64
 3   Advertising  400 non-null    int64
 4   Population   400 non-null    int64
 5   Price        400 non-null    int64
 6   ShelveLoc    400 non-null    int64
 7   Age          400 non-null    int64
 8   Education    400 non-null    int64
 9   Urban        400 non-null    int64
 10  US           400 non-null    int64
dtypes: int64(11)
memory usage: 34.5 KB


In [7]:
# dataset tozalangandan keyin uni input va outputga bo'lib olamiz

x = df.drop('US', axis=1)
y = df['US']


In [8]:
# biz scaling ni amalga oshiramiz
scaler = StandardScaler()

x_scaled = scaler.fit_transform(x)


In [9]:
# datasetimizni train, test va baxolash uchun 0.7:0.15:0.15 bo'lib olamiz

x_train,x_temp,y_train, y_temp=train_test_split(x_scaled,y,test_size=0.3, random_state=42)
x_val,x_test,y_val, y_test=train_test_split(x_temp,y_temp,test_size=0.5,random_state=42)

# Logistik regressiondan foydalanamiz

In [10]:
# model train qilamiz

model=LogisticRegression(max_iter=1000,solver='lbfgs')
model.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [11]:
#Predicting
y_pred=model.predict(x_test)

y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0])

In [12]:
# model qanchalik aniq ishlashini tekshiramiz
accuracy_score=accuracy_score(y_test,y_pred)


print(f'Accuracy: {accuracy_score:.2f}')


Accuracy: 0.90


# Decision Treedan foydalanamiz

In [9]:
# model train qilamiz

model = DecisionTreeClassifier(random_state=42)
model.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [10]:
# Predicting
y_pred = model.predict(x_test)

y_pred


array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0])

In [11]:
# # model qanchalik aniq ishlashini tekshiramiz

accuracy_score = accuracy_score(y_test, y_pred)

print(f'Accuracy: {accuracy_score:.2f}')

Accuracy: 0.87


In [10]:
# K-fold cross-validation (k=5)
cv_scores = cross_val_score(model, x_scaled, y, cv=5)  # cv=5 means 5-fold cross-validation
avg_cv_scores=np.mean(cv_scores)

#O'rtacha qiymat topamiz
avg_cv_scores

0.8549999999999999

In [11]:
# modelimi accuracy 85% chiqganligi sababli biz Hyper paramet tuning amalga oshiramiz, (GridSearchCV)

param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10, 20, 30, 40],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': [None, 'sqrt', 'log2'],
}


grid_search = GridSearchCV(estimator=model, param_grid=param_grid,
                           cv=5, n_jobs=-1, verbose=2)

grid_search.fit(x_train, y_train)


print("Best hyperparameters found: ", grid_search.best_params_)

Fitting 5 folds for each of 270 candidates, totalling 1350 fits
Best hyperparameters found:  {'criterion': 'gini', 'max_depth': None, 'max_features': None, 'min_samples_leaf': 4, 'min_samples_split': 10}


In [12]:
#Hyper paramater tuningdan so'ng natijalarni ko'ramiz

best_model = grid_search.best_estimator_
y_pred = best_model.predict(x_test)

y_pred

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0])

In [13]:
# # model qanchalik aniq ishlashini tekshiramiz

accuracy_score = accuracy_score(y_test, y_pred)

print(f'Accuracy: {accuracy_score:.2f}')

Accuracy: 0.90


# KNN dan foydalanamiz

In [9]:
# model train qilamiz

model = KNeighborsClassifier(n_neighbors=5)  # k= 5 nearest neighbors
model.fit(x_train, y_train)

KNeighborsClassifier()

In [11]:
# Predicting

y_pred = model.predict(x_test)

y_pred

array([0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1])

In [12]:
# # model qanchalik aniq ishlashini tekshiramiz

accuracy_score = accuracy_score(y_test, y_pred)


print(f'Accuracy: {accuracy_score:.2f}')

Accuracy: 0.68


In [13]:
# Classification Report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.50      0.53      0.51        19
           1       0.78      0.76      0.77        41

    accuracy                           0.68        60
   macro avg       0.64      0.64      0.64        60
weighted avg       0.69      0.68      0.69        60



In [14]:
# k-fold K=10
cv_scores = cross_val_score(model, x_scaled, y, cv=10)  # 10-fold cross-validation


# Print the results of cross-validation
print(f'Cross-validation scores for each fold: {cv_scores}')
print(f'Mean accuracy from cross-validation: {cv_scores.mean():.2f}')
print(f'Standard deviation of cross-validation scores: {cv_scores.std():.2f}')

Cross-validation scores for each fold: [0.675 0.725 0.725 0.725 0.675 0.775 0.75  0.725 0.725 0.75 ]
Mean accuracy from cross-validation: 0.72
Standard deviation of cross-validation scores: 0.03


# Random Forest dan foydalanamiz

In [10]:
# model train qilamiz

model = RandomForestClassifier(random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [11]:
# Predicting
y_pred = model.predict(x_test)

y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0])

In [12]:
# # model qanchalik aniq ishlashini tekshiramiz

accuracy_score = accuracy_score(y_test, y_pred)

print(f'Accuracy: {accuracy_score:.2f}')

Accuracy: 0.90
